from app.schemas.pipeline import (
    PipelineBlueprint,
    NumericImputerStrategy,
    NumericScalerStrategy,
    CategoricalImputerStrategy,
    CategoricalEncoderStrategy
)
from app.schemas.dataset import TaskType

class CodeGenerator:
    @classmethod
    def generate_pipeline_script(
        cls,
        blueprint: PipelineBlueprint,
        numeric_cols: list[str],
        categorical_cols: list[str],
        target_col: str,
        task_type: TaskType
    ) -> str:
        # Determine numeric imports & steps
        num_steps = []
        if numeric_cols:
            if blueprint.num_imputer == NumericImputerStrategy.MEAN:
                num_steps.append("        ('num_imputer', SimpleImputer(strategy='mean'))")
            elif blueprint.num_imputer == NumericImputerStrategy.MEDIAN:
                num_steps.append("        ('num_imputer', SimpleImputer(strategy='median'))")
            elif blueprint.num_imputer == NumericImputerStrategy.KNN:
                num_steps.append("        ('num_imputer', KNNImputer(n_neighbors=5))")

            if blueprint.num_scaler == NumericScalerStrategy.STANDARD:
                num_steps.append("        ('num_scaler', StandardScaler())")
            elif blueprint.num_scaler == NumericScalerStrategy.ROBUST:
                num_steps.append("        ('num_scaler', RobustScaler())")
            elif blueprint.num_scaler == NumericScalerStrategy.MINMAX:
                num_steps.append("        ('num_scaler', MinMaxScaler())")
            elif blueprint.num_scaler == NumericScalerStrategy.POWER:
                num_steps.append("        ('num_scaler', PowerTransformer(method='yeo-johnson'))")

        # Determine categorical imports & steps
        cat_steps = []
        if categorical_cols:
            if blueprint.cat_imputer == CategoricalImputerStrategy.MOST_FREQUENT:
                cat_steps.append("        ('cat_imputer', SimpleImputer(strategy='most_frequent'))")
            elif blueprint.cat_imputer == CategoricalImputerStrategy.CONSTANT:
                cat_steps.append("        ('cat_imputer', SimpleImputer(strategy='constant', fill_value='missing'))")

            if blueprint.cat_encoder == CategoricalEncoderStrategy.ONEHOT:
                cat_steps.append("        ('cat_encoder', OneHotEncoder(handle_unknown='ignore', sparse_output=False))")
            elif blueprint.cat_encoder == CategoricalEncoderStrategy.ORDINAL:
                cat_steps.append("        ('cat_encoder', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1))")

        # Select model class
        if task_type == TaskType.CLASSIFICATION:
            model_import = "from sklearn.ensemble import RandomForestClassifier"
            model_step = "RandomForestClassifier(n_estimators=100, random_state=42)"
        else:
            model_import = "from sklearn.ensemble import RandomForestRegressor"
            model_step = "RandomForestRegressor(n_estimators=100, random_state=42)"

        num_steps_code = ",\n".join(num_steps) if num_steps else "        ('passthrough', 'passthrough')"
        cat_steps_code = ",\n".join(cat_steps) if cat_steps else "        ('passthrough', 'passthrough')"

        script = f'''# ==============================================================================
# Auto-generated by DataLens AI
# Recommended Preprocessing Pipeline: {blueprint.name}
# Description: {blueprint.description}
# ==============================================================================

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer, KNNImputer
from sklearn.preprocessing import (
    StandardScaler,
    RobustScaler,
    MinMaxScaler,
    PowerTransformer,
    OneHotEncoder,
    OrdinalEncoder
)
{model_import}

# Feature definitions
NUMERIC_FEATURES = {repr(numeric_cols)}
CATEGORICAL_FEATURES = {repr(categorical_cols)}
TARGET_COLUMN = {repr(target_col)}

def build_datalens_pipeline() -> Pipeline:
    transformers = []
    
    if NUMERIC_FEATURES:
        transformers.append((
            "numeric",
            Pipeline(steps=[
{num_steps_code}
            ]),
            NUMERIC_FEATURES
        ))
        
    if CATEGORICAL_FEATURES:
        transformers.append((
            "categorical",
            Pipeline(steps=[
{cat_steps_code}
            ]),
            CATEGORICAL_FEATURES
        ))

    preprocessor = ColumnTransformer(
        transformers=transformers,
        remainder="drop"
    )

    full_pipeline = Pipeline(steps=[
        ("preprocessor", preprocessor),
        ("model", {model_step})
    ])

    return full_pipeline

if __name__ == "__main__":
    import sys
    if len(sys.argv) < 2:
        print("Usage: python pipeline.py <path_to_dataset.csv>")
        sys.exit(1)

    data_path = sys.argv[1]
    df = pd.read_csv(data_path)
    X = df.drop(columns=[TARGET_COLUMN])
    y = df[TARGET_COLUMN]

    pipeline = build_datalens_pipeline()
    print("Fitting recommended DataLens pipeline...")
    pipeline.fit(X, y)
    print("Pipeline successfully fitted on dataset!")
'''
        return script